[project]
name = "api"
version = "0.1.0"
requires-python = ">=3.10"

dependencies = [
    "fastapi>=0.95,<0.100",
    "pydantic<2",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
    "httpx>=0.27.0",

    # ğŸ”½ version compatible Starlette < 0.28
    "prometheus-fastapi-instrumentator>=6.1,<7.0",
    "prometheus-client>=0.16,<0.21",
]

[project.optional-dependencies]
dev = [
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "pytest-cov>=7.0.0",
]

[tool.pytest.ini_options]
testpaths = ["../tests"]
pythonpath = ["."]
asyncio_mode = "strict"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "pytest-cov>=7.0.0",
]
